---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-istio
  namespace: istio-system
spec:
  values:
    global:
      azure:
        tenant: b7be7686-6f97-4db7-9081-a23cf09a96b5
        appid: e023491f-8d61-4f69-92d1-c01e3d5fb8a1
