---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: schema-service
  namespace: osdu-azure
spec:
  values:
    ingress:
      dns: osdu-self-dplchfih-pljm-gw.southcentralus.cloudapp.azure.com
    configuration:
    - service: schema
      repository: osduselfcplchf72s0cr.azurecr.io/schema
      path: /api/schema-service/v1/*
      probe:
        path: /api/schema-service/v1/swagger-ui.html
        port: http
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/schema-service/v1/swagger-resources/*"
          - "/api/schema-service/v1/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: spring_application_name
        value: "schema"
      - name: server.servlet.contextPath
        value: "/api/schema-service/v1/"
      - name: server_port
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: cosmosdb_database
        value: "osdu-db"
      - name: LOG_PREFIX
        value: "schema"
      - name: entitlements_service_endpoint
        value: "http://entitlements/api/entitlements/v2"
      - name: entitlements_service_api_key
        value: "OBSOLETE"
      - name: partition_service_endpoint
        value: "http://partition/api/partition/v1"
      - name: shared_partition
        value: "opendes"
      - name: azure_istioauth_enabled
        value: "true"
      - name: event_grid_enabled
        value: "false"
      - name: event_grid_topic
        value: "schemachangedtopic"
      - name: azure_activedirectory_AppIdUri
        value: "api://e023491f-8d61-4f69-92d1-c01e3d5fb8a1"
      - name: azure_paas_podIdentity_isEnabled
        value: "false"
      - name: KEYVAULT_URI
        config:
          name: osdu-svc-config
          key: ENV_KEYVAULT
      - name: aad_client_id
        secret:
          name: active-directory
          key: application-appid
      - name: appinsights_key
        secret:
          name: central-logging
          key: appinsights
