---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  values:
    fullnameOverride: osdu-svc
    azure:
      tenant: b7be7686-6f97-4db7-9081-a23cf09a96b5
      subscription: f726e0f9-96bc-4f6d-bb3d-ccf0ae64b662
      resourcegroup: osdu-self-cplchfih-72s0-rg
      identity: osdu-self-cplchfih-72s0-osdu-identity
      identity_id: f6f478b0-68af-4cfc-a5c8-880dab979994
      keyvault: osdu-self-cplchf-72s0-kv
      appid: e023491f-8d61-4f69-92d1-c01e3d5fb8a1
      oidAuthEnabled: false
    resourceLimits:
      defaultCpuRequests: "100m"
      defaultMemoryRequests: "800Mi"
      defaultCpuLimits: "1000m"
      defaultMemoryLimits: "2Gi"
    identity:
      name: osdu-identity
